
set(CURRENT_TEST model)
set(CURRENT_CATEGORY api)
list(APPEND CSIM_TESTS ${CURRENT_TEST})
set(${CURRENT_TEST}_SRCS
  ${CURRENT_TEST}/model.cpp
)

set(SBML_MODEL_RESOURCE "${CMAKE_CURRENT_SOURCE_DIR}/resources/BIOMD0000000020.xml")

