FIND_PATH(CELLML_INCLUDE_DIR IfaceCellML_APISPEC.hxx
    ${CSIM_DEPENDENCY_DIR}/include
)

FIND_LIBRARY(CELLML_LIBRARY cellml
    ${CSIM_DEPENDENCY_DIR}/lib
)

FIND_LIBRARY(CCGS_LIBRARY ccgs
    ${CSIM_DEPENDENCY_DIR}/lib
)
FIND_LIBRARY(ANNO_TOOLS_LIBRARY annotools
    ${CSIM_DEPENDENCY_DIR}/lib
)
FIND_LIBRARY(CEVAS_LIBRARY cevas
    ${CSIM_DEPENDENCY_DIR}/lib
)
FIND_LIBRARY(CUSES_LIBRARY cuses
    ${CSIM_DEPENDENCY_DIR}/lib
)
FIND_LIBRARY(MALAES_LIBRARY malaes
    ${CSIM_DEPENDENCY_DIR}/lib
)

IF (CELLML_INCLUDE_DIR AND CELLML_LIBRARY AND CCGS_LIBRARY AND ANNO_TOOLS_LIBRARY AND CEVAS_LIBRARY AND CUSES_LIBRARY AND MALAES_LIBRARY)
   SET(CELLML_LIBRARIES ${CELLML_LIBRARY} ${CCGS_LIBRARY} ${ANNO_TOOLS_LIBRARY} ${CEVAS_LIBRARY} ${CUSES_LIBRARY} ${MALAES_LIBRARY})
   SET(CELLML_FOUND TRUE)
ENDIF ()

IF (CELLML_FOUND)
   IF (NOT CELLML_FIND_QUIETLY)
      MESSAGE(STATUS "Found CELLML: ${CELLML_LIBRARIES}")
   ENDIF ()
ELSE ()
   IF (CELLML_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find CellML API")
   ELSE ()
      MESSAGE(STATUS "CellML API not found")
   ENDIF ()
ENDIF ()
